.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BODYDECODER" "" "September 2010" "" ""
.
.SH "NAME"
\fBbodyDecoder\fR
.
.SH "Body Decoder"
The \fIbodyDecoder\fR middleware sniffs the \fIContent\-Type\fR header, and decodes the request body appropriately\. Supported by default are the \fIapplication/x\-www\-form\-urlencoded\fR, and \fIapplication/json\fR content types\. To extend simply:
.
.IP "" 4
.
.nf

connect\.bodyDecoder\.decode[\'some\-mime/type\'] = function(str){
    return \'whatever\';
};
.
.fi
.
.IP "" 0
.
.SS "See Also"
.
.IP "\(bu" 4
methodOverride
.
.IP "" 0

