.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "COMPILER" "" "June 2010" "" ""
.
.SH "Compiler"
The \fIcompiler\fR middleware compiles files that have not yet been compiled, or have been modified\. Good examples of this are \fIsass\fR and \fIless\fR, both of which compile to css\. The compiled data is written to disk, and serving is delegated to the \fIstatic\fR middleware, therefore the \fIdest\fR should be accessible (or the same) as \fIstatic\fR\'s \fIroot\fR option\.
.
.IP "" 4
.
.nf

connect\.createServer(
    connect\.compiler({ src: __dirname + \'/public\', enable: [\'sass\'] })
);
.
.fi
.
.IP "" 0
.
.SS "Options"
.
.nf

src      Root directory from which to compile files\. Defaults to CWD\.
dest     Destination directory of compiled files, defaults to src or CWD\.
enable   Enabled compilers, currently supported are \"sass\", and \"less\"\.
.
.fi
.
.SS "Supported Compilers"
.
.IP "\(bu" 4
sass
.
.IP "\(bu" 4
less
.
.IP "" 0
.
.SS "Environment Variables"
.
.nf

\-\-compilerSrc
\-\-compilerDest
.
.fi
.
.SS "Links"
.
.IP "\(bu" 4
Sass\.js \fIhttp://github\.com/visionmedia/sass\.js\fR
.
.IP "\(bu" 4
Less\.js \fIhttp://github\.com/cloudhead/less\.js\fR
.
.IP "" 0
.
.SS "See Also"
.
.IP "\(bu" 4
staticProvider
.
.IP "" 0

