.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "FLASH" "" "June 2010" "" ""
.
.SH "Flash"
The \fIflash\fR middleware provides persistent messaging\. This middleware requires \fIsession\fR to function\.
.
.IP "" 4
.
.nf

req\.flash(\'info\', \'email sent\');
req\.flash(\'error\', \'email delivery failed\');
req\.flash(\'info\', \'email re\-sent\');
// => 2

req\.flash(\'info\');
// => [\'email sent\', \'email re\-sent\']

req\.flash(\'info\');
// => []

req\.flash();
// => { error: [\'email delivery failed\'], info: [] }
.
.fi
.
.IP "" 0
.
.SH "See Also"
.
.IP "\(bu" 4
cookieDecoder
.
.IP "\(bu" 4
session
.
.IP "" 0

