.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "FORMAT" "" "June 2010" "" ""
.
.SH "Format"
The \fIformat\fR middleware populates \fBreq\.format\fR from urls such as \fI/products\.json\fR where the \fBreq\.url\fR becomes \fI/products\fR and \fBreq\.format\fR becomes \fIjson\fR\.
