.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FORMAT" "" "June 2010" "" ""
.
.SH "NAME"
\fBformat\fR
.
.SH "Format"
The \fIformat\fR middleware populates \fBreq\.format\fR from urls such as \fI/products\.json\fR where the \fBreq\.url\fR becomes \fI/products\fR and \fBreq\.format\fR becomes \fIjson\fR\.
