.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "JSONRPC" "" "August 2010" "" ""
.
.SH "JSON\-RPC"
The \fIjsonrpc\fR middleware provides JSON\-RPC 2\.0 support\. Below is an example exposing the \fIadd\fR and \fIsub\fR methods:
.
.IP "" 4
.
.nf

var math = {
    add: function(a, b, fn){
        fn(null, a + b);
    },
    sub: function(a, b, fn){
        fn(null, a \- b);
    }
};

var date = {
    time: function(fn){
        fn(null, new Date()\.toUTCString());
    }
};

connect\.createServer(
    connect\.jsonrpc(math, date)
);
.
.fi
.
.IP "" 0
.
.P
When you wish to pass an exception simply invoke \fBfn(err)\fR, or pass the error code \fBfn(jsonrpc\.INVALID_PARAMS)\fR\. Otherwise \fBfn(null, result)\fR will respond with the given results\.
.
.SS "Features"
.
.IP "\(bu" 4
async support
.
.IP "\(bu" 4
batch request support
.
.IP "\(bu" 4
variable argument length
.
.IP "\(bu" 4
named parameter support
.
.IP "" 0

