.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "LESS" "" "June 2010" "" ""
.
.SH "Less"
The \fIless\fR middleware compiles and serves \fI*\.less\fR files as css\. Less itself is not bundled with Connect, so you must have it installed and available to node\.
.
.IP "" 4
.
.nf

connect\.createServer([
    { provider: \'less\', root: __dirname + \'/public\', match: /\\\.css$/ }
]);
.
.fi
.
.IP "" 0
.
.SS "Options"
.
.nf

root   Root directory from which to serve sass\. Defaults to CWD
match  RegExp used to match request urls\. Defaults to /\\\.less$/
.
.fi
.
.SS "Environment Variables"
.
.nf

\-\-lessRoot
.
.fi
.
.SS "See Also"
.
.IP "\(bu" 4
sass
.
.IP "" 0
.
.SS "Links"
.
.IP "\(bu" 4
Less\.js \fIhttp://github\.com/cloudhead/less\.js\fR
.
.IP "" 0

