.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "RESPONSETIME" "" "June 2010" "" ""
.
.SH "Response Time"
The \fIresponseTime\fR middleware responds with the \fIX\-Response\-Time\fR header indicating the duration of the response in milliseconds\. This middleware typically should sit at the top of your stack\.
