.\" generated with Ronn/v0.6.6
.\" http://github.com/rtomayko/ronn/
.
.TH "SASS" "" "June 2010" "" ""
.
.SH "Sass"
The \fIsass\fR middleware compiles \fI*\.sass\fR files as css, these files are written to disk, and automatically re\-compiled when altered\. \fIsass\fR itself does not serve the file, it delegates to the \fIstatic\fR middleware, therefore the \fIroot\fR option should be accessible to \fIstatic\fR\.
.
.P
Sass itself is not bundled with Connect, so you must have it installed and available to node\.
.
.IP "" 4
.
.nf

connect\.createServer([
    { provider: \'sass\', root: __dirname + \'/public\' }
]);
.
.fi
.
.IP "" 0
.
.SS "Options"
.
.nf

root   Root directory from which to compile sass\. Defaults to CWD
.
.fi
.
.SS "Environment Variables"
.
.nf

\-\-sassRoot
.
.fi
.
.SS "Links"
.
.IP "\(bu" 4
Sass\.js \fIhttp://github\.com/visionmedia/sass\.js\fR
.
.IP "" 0
.
.SS "See Also"
.
.IP "\(bu" 4
static
.
.IP "" 0

