.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STATICPROVIDER" "" "September 2010" "" ""
.
.SH "NAME"
\fBstaticProvider\fR
.
.SH "Static Provider"
The \fIstaticProvider\fR middleware provides static file serving to the given \fIroot\fR directory defaulting to the \fBCWD\fR, for example:
.
.IP "" 4
.
.nf

connect\.createServer(
    connect\.staticProvider(__dirname + \'/public\')
);
.
.fi
.
.IP "" 0
.
.P
Alternatively if specifying additional options:
.
.IP "" 4
.
.nf

connect\.createServer(
    connect\.staticProvider({
        root: __dirname + \'/public\',
        exclude: /\.*\e/server\e/\.*/
    })
);
.
.fi
.
.IP "" 0
.
.SS "Options"
.
.nf

root            Root directory from which to serve static files\.
maxAge          Browser cache maxAge in milliseconds
cache           When true cache files in memory indefinitely, until invalidated by
                a conditional GET request\. When given, maxAge will be derived from
                this value\.
exclude         Regular expression used to prevent specific paths from being returned\.
.
.fi
.
.SS "Environment Variables"
.
.nf

\-\-staticRoot
.
.fi

